{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3548eaf8-007a-45ba-a9f6-234f3d58933f",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    " 是导入 Python 标准库中的 Unicode 数据库模块\n",
    " # 判断字符类型\n",
    "unicodedata.category('A')      # 'Lu'（大写字母）\n",
    "unicodedata.category('a')      # 'Ll'（小写字母）\n",
    "unicodedata.category('1')      # 'Nd'（十进制数字）\n",
    "\"\"\"\n",
    "import unicodedata"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1b143aa5-12f3-4c6b-a8ca-52f8b40da0d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_stats(ids, counts=None):\n",
    "    \"\"\"\n",
    "    [1, 2, 3, 1, 2] -> {(1, 2): 2, (2, 3): 1, (3, 1): 1}\n",
    "    \"\"\"\n",
    "    counts = {} if counts is None else counts\n",
    "    for pair in zip(ids, ids[1:]): # 巧妙的方式获得相邻字节\n",
    "        counts[pair] = counts.get(pair, 0) + 1 #counts.get(pair, 0) pair不在counts中返回0\n",
    "    return counts"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ff41ca90-f5c3-4e2d-95df-13e41b28f26d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "b'\\xf0\\x9f\\x8c\\x9e'\n"
     ]
    }
   ],
   "source": [
    "def merge(ids, pair, idx):\n",
    "    \"\"\"\n",
    "    通过get_stats返回相邻pair，找到出现频率最高的相邻pair，把这种相邻pair合并，\n",
    "    合并后就属于一项merge规则\n",
    "    Example: ids=[1, 2, 3, 1, 2], pair=(1, 2), idx=4 -> [4, 3, 4]\n",
    "    \"\"\"\n",
    "    newids = []\n",
    "    i = 0\n",
    "    while i < len(ids):\n",
    "        # if not at the very last position AND the pair matches, replace it\n",
    "        if ids[i] == pair[0] and i < len(ids) - 1 and ids[i+1] == pair[1]:\n",
    "            newids.append(idx)\n",
    "            i += 2\n",
    "        else:\n",
    "            newids.append(ids[i])\n",
    "            i += 1\n",
    "    return newids"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e7e8bd26-7d1e-4733-a352-f0223f7e726e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "# Token 可能包含各种字节\n",
    "token = b'\\n'        # 换行符\n",
    "token = b'\\x00'      # NULL 字符\n",
    "token = b'\\t'        # Tab\n",
    "token = b'\\x1b[31m'  # ANSI 转义码\n",
    "\n",
    "# 如果直接打印\n",
    "print(token.decode('utf-8'))\n",
    "# 输出：会真的换行！会破坏终端显示！\n",
    "例如 \"Hello\\nWorld\"  经过处理得到  Hello\\u000aWorld  ← \\n 被转义成 \\u000a\n",
    "\"\"\"\n",
    "\n",
    "def replace_control_characters(s: str) -> str:\n",
    "    # 我们不想打印控制字符\n",
    "    # 因为它们会扭曲输出（比如 \\n 或者更糟的）\n",
    "    \n",
    "    chars = []\n",
    "    for ch in s:\n",
    "        # 检查字符的 Unicode 类别\n",
    "        if unicodedata.category(ch)[0] != \"C\":\n",
    "            # 类别不是 \"C\" (Control) → 正常字符\n",
    "            chars.append(ch)\n",
    "        else:\n",
    "            # 类别是 \"C\" → 控制字符，转义显示\n",
    "            chars.append(f\"\\\\u{ord(ch):04x}\")\n",
    "    \n",
    "    return \"\".join(chars)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "c89538eb-49d5-488f-b908-f22d7c759129",
   "metadata": {},
   "outputs": [],
   "source": [
    "def render_token(t: bytes) -> str:\n",
    "    # pretty print a token, escaping control characters\n",
    "    s = t.decode('utf-8', errors='replace')\n",
    "    s = replace_control_characters(s)\n",
    "    return s"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "88967d85-cc7f-4d42-8fd6-6023fd4014e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Tokenizer:\n",
    "\n",
    "    def __init__(self):\n",
    "\n",
    "        self.merges = {} # (int, int) -> int 合并规则\n",
    "        self.pattern = \"\" # 正则，用于切分字符\n",
    "        self.special_tokens = {} # str -> int, 用于特殊token切分 {'<|endoftext|>': 100257}\n",
    "        self.vocab = self._build_vocab() # int -> bytes\n",
    "\n",
    "    def train(self, text, vocab_size, verbose=False):\n",
    "        # 接口\n",
    "        raise NotImplementedError\n",
    "\n",
    "    def encode(self, text):\n",
    "      \n",
    "        raise NotImplementedError\n",
    "\n",
    "    def decode(self, ids):\n",
    "      \n",
    "        raise NotImplementedError\n",
    "\n",
    "    def _build_vocab(self):\n",
    "        # vocab 是字节和码点的映射\n",
    "        vocab = {idx: bytes([idx]) for idx in range(256)}\n",
    "        # 遍历merge规则，把需要合并的组合合并起来存储vocab当中\n",
    "        for (p0, p1), idx in self.merges.items():\n",
    "            vocab[idx] = vocab[p0] + vocab[p1]\n",
    "        # 对于特殊token也要存储vocab当中\n",
    "        for special, idx in self.special_tokens.items():\n",
    "            vocab[idx] = special.encode(\"utf-8\")\n",
    "        return vocab\n",
    "\n",
    "    def save(self, file_prefix):\n",
    "        \"\"\"\n",
    "        形成两个文件: file_prefix.vocab and file_prefix.model\n",
    "        1. my_tokenizer.model  → 给机器用（程序加载）\n",
    "        2. my_tokenizer.vocab  → 给人类用（查看、调试）\n",
    "\n",
    "        my_tokenizer.model 例子\n",
    "        bpe v1\n",
    "        '(?i:[sdmt]|ll|ve|re)|[^\\r\\n\\p{L}\\p{N}]?+\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]++[\\r\\n]*|\\s*[\\r\\n]|\\s+(?!\\S)|\\s+\n",
    "        1\n",
    "        <|endoftext|> 261\n",
    "        108 108\n",
    "        101 108\n",
    "        111 32\n",
    "        119 111\n",
    "        32 119\n",
    "\n",
    "        my_tokenizer.vocab例子\n",
    "        [\\u0000] 0\n",
    "        [\\u0001] 1\n",
    "        ...\n",
    "        [e] 101\n",
    "        ...\n",
    "        [l] 108\n",
    "        ...\n",
    "        [o] 111\n",
    "        ...\n",
    "        [w] 119\n",
    "        ...\n",
    "        [\\u0020] 32\n",
    "        ...\n",
    "        [\\u00ff] 255\n",
    "        [l][l] -> [ll] 256\n",
    "        [e][l] -> [el] 257\n",
    "        [o][\\u0020] -> [o ] 258\n",
    "        \"\"\"\n",
    "        # write the model: to be used in load() later\n",
    "        model_file = file_prefix + \".model\"\n",
    "        with open(model_file, 'w') as f:\n",
    "            # 写入版本号\n",
    "            f.write(\"bpe v1\\n\")\n",
    "            f.write(f\"{self.pattern}\\n\")#这是bpe的核心，切分正则表达式\n",
    "            # 特殊token\n",
    "            f.write(f\"{len(self.special_tokens)}\\n\")\n",
    "            for special, idx in self.special_tokens.items():\n",
    "                f.write(f\"{special} {idx}\\n\")\n",
    "            # 把merge规则也写入\n",
    "            for idx1, idx2 in self.merges:\n",
    "                f.write(f\"{idx1} {idx2}\\n\")\n",
    "        \n",
    "        vocab_file = file_prefix + \".vocab\"\n",
    "        inverted_merges = {idx: pair for pair, idx in self.merges.items()}\n",
    "        with open(vocab_file, \"w\", encoding=\"utf-8\") as f:\n",
    "            for idx, token in self.vocab.items():\n",
    "                s = render_token(token)\n",
    "                if idx in inverted_merges:\n",
    "                    idx0, idx1 = inverted_merges[idx]\n",
    "                    s0 = render_token(self.vocab[idx0])\n",
    "                    s1 = render_token(self.vocab[idx1])\n",
    "                    f.write(f\"[{s0}][{s1}] -> [{s}] {idx}\\n\")\n",
    "                else:\n",
    "                    f.write(f\"[{s}] {idx}\\n\")\n",
    "\n",
    "    def load(self, model_file):\n",
    "        \"\"\"按照.model文件的写入的格式，把相关信息加载出来\"\"\"\n",
    "        assert model_file.endswith(\".model\")\n",
    "        # read the model file\n",
    "        merges = {}\n",
    "        special_tokens = {}\n",
    "        idx = 256\n",
    "        with open(model_file, 'r', encoding=\"utf-8\") as f:\n",
    "            # read the version\n",
    "            version = f.readline().strip()\n",
    "            assert version == \"bpe v1\"\n",
    "            # read the pattern\n",
    "            self.pattern = f.readline().strip()\n",
    "            # read the special tokens\n",
    "            num_special = int(f.readline().strip())\n",
    "            for _ in range(num_special):\n",
    "                special, special_idx = f.readline().strip().split()\n",
    "                special_tokens[special] = int(special_idx)\n",
    "            # read the merges\n",
    "            for line in f:\n",
    "                idx1, idx2 = map(int, line.split())\n",
    "                merges[(idx1, idx2)] = idx\n",
    "                idx += 1\n",
    "        self.merges = merges\n",
    "        self.special_tokens = special_tokens\n",
    "        self.vocab = self._build_vocab()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a42ef1a2-46da-4afe-94ab-67544d048a3c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
